# Generated by Django 5.0.3 on 2024-03-27 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role_overview', models.TextField()),
                ('role_requirements_and_preferences', models.TextField()),
                ('action_steps', models.TextField()),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 6, 25, 14, 51, 17, 221521, tzinfo=datetime.timezone.utc))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employerorganization',
            name='employer_org_description_box',
            field=models.TextField(default='Describe your organization, but not a specific role or requirements'),
        ),
    ]
