# Generated by Django 5.0.3 on 2024-03-27 15:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_catalog', '0002_jobposting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_catalog.employerorganization'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 15, 11, 33, 645613, tzinfo=datetime.timezone.utc)),
        ),
    ]
