# Generated by Django 5.0.3 on 2024-03-29 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_catalog', '0005_alter_jobposting_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerorganization',
            name='representative_claim_token',
            field=models.CharField(default='join', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 5, 16, 9, 24453, tzinfo=datetime.timezone.utc)),
        ),
    ]
