# Generated by Django 5.0.3 on 2024-03-29 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_catalog', '0006_employerorganization_representative_claim_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 14, 35, 36, 776409, tzinfo=datetime.timezone.utc)),
        ),
    ]
