# Generated by Django 5.0.3 on 2024-04-01 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_catalog', '0007_alter_jobposting_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 8, 44, 27, 401214, tzinfo=datetime.timezone.utc)),
        ),
    ]
